version: '3'
services:
  # Consul server on VM
  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/config/consul.hcl"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8600
      - 8502
      - 8500:8500
      - 8302
      - 8301
      - 8300
    networks:
      onprem:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  web:
    image: nicholasjackson/fake-service:vm-v0.7.8
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: http://localhost:9091
      NAME: Web
      MESSAGE: "Hello World"
      CONSUL_SERVER: 10.5.0.2
      CONSUL_DATACENTER: onprem
      SERVICE_ID: web-v1
    
    volumes:
      - "./server_config/web.hcl:/config/web.hcl"

    networks:
      onprem:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090

  gateway:
    image: nicholasjackson/consul-envoy:v1.6.1-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
    command: [
      "consul",
      "connect", "envoy",
      "-mesh-gateway",
      "-register",
      "-address", "10.5.0.33:8443",
      "-wan-address", "192.169.7.33:8443",
      "--",
      "-l", "debug"]
    networks:
      onprem:
        ipv4_address: 10.5.0.33
      wan:
        ipv4_address: 192.169.7.33

networks:
  onprem:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24