---
version: "3.3"
services:

  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/config/config.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  web:
    image: nicholasjackson/fake-service:vm-v0.7.8
    environment:
      CONSUL_GRPC_ADDR: localhost:8502
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: http://api:9090
      NAME: Web
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
      CONSUL_SERVER: 10.5.0.2
      CONSUL_DATACENTER: dc1
      SERVICE_ID: web-v1

    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090
  
  api:
    image: nicholasjackson/fake-service:vm-v0.7.8
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      NAME: API
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
      CONSUL_SERVER: 10.5.0.2
      CONSUL_DATACENTER: dc1
      SERVICE_ID: api-v1

    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 9091:9090

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
