version: '3'
services:
  # Consul server on VM
  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/config/consul.hcl"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8600
      - 8502
      - 8500:8500
      - 8302
      - 8301
      - 8300
    networks:
      onprem:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

networks:
  onprem:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24
