---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: currency
        image: nicholasjackson/fake-service:v0.7.7
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "currency (cloud)"
        - name: "MESSAGE"
          value: "currency response"
        - name: "HTTP_CLIENT_KEEP_ALIVES"
          value: "false"